server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Vue Router 需要這段
    # 所有路由都返回 index.html，讓 Vue 前端處理路由
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 靜態資源快取設定
    location /assets {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
